# Generated by Django 5.2.4 on 2025-08-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory', models.PositiveIntegerField()),
            ],
        ),
    ]
